services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  skai:
    build:
      context: ./skai
      dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY=abcdxyz
    ports:
      - "8000:8000"
    depends_on:
      - frontend
    volumes:
      - ./skai:/app
