name: Build & Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build-and-push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Debug event
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Merged: ${{ github.event.pull_request.merged }}"
          echo "Ref: ${{ github.ref }}"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Node service
        uses: docker/build-push-action@v6
        with:
          context: ./node-service
          file: ./node-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nasa_backend:latest
      - name: Build and push React service
        uses: docker/build-push-action@v6
        with:
          context: ./react-service
          file: ./react-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nasa_frontend:latest
      - name: Build and push Django service
        uses: docker/build-push-action@v6
        with:
          context: ./django-service
          file: ./django-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nasa_skai:latest